@baseUrl = http://localhost:5000/api

### 1. Registrasi Akun Customer Baru
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Edo Customer",
  "email": "edo_customer@mail.com",
  "password": "password123",
  "role": "customer",
  "phoneNumber": "08123456789"
}

###

### 2. Registrasi Akun Owner Baru
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Hendra Owner Lapangan",
  "email": "hendra_owner@mail.com",
  "password": "password123",
  "role": "owner",
  "phoneNumber": "08987654321"
}

###

### 3. Jalankan Login User
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "edo_customer@mail.com",
  "password": "password123"
}

###

### 4. Tes Akses Profil Tanpa Token (Harus Gagal 401)
GET {{baseUrl}}/auth/me

###

### 5. Tes Akses Profil dengan Token yang Benar (Harus Sukses)
# Langkah: Jalankan login dulu di request no 3, lalu jalankan request ini
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "edo_customer@mail.com",
  "password": "password123"
}

### Ambil token hasil login di atas secara otomatis
@tokenAktif = {{loginUser.response.body.data.token}}

GET {{baseUrl}}/auth/me
Authorization: Bearer {{tokenAktif}}